name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        uses: actions/setup-node@v3
        with:
          node-version: 14
      -
        run: npm i
      -
        run: npm deploy
